sudo: required
dist: trusty
os:   linux
services:
    - docker
language: cpp
compiler:
    - gcc
before_install:
    - docker pull dashproject/ci:mpich
script:
    - sh ./dash/scripts/travisci/run-docker.sh Release
    - cat ./dash-ci.log | (grep "FAIL" || return 0) || return 1
    - sh ./dash/scripts/travisci/run-docker.sh Minimal
    - cat ./dash-ci.log | (grep "FAIL" || return 0) || return 1
    - sh ./dash/scripts/travisci/run-docker.sh Nasty
    - cat ./dash-ci.log | (grep "FAIL" || return 0) || return 1
after_script:
    - cat ./build-ci/*/*/test_mpi.log | grep -v "LOG"
after_failure:
    - cat ./dash-ci.err
    - cat ./build-ci/*/*/build.log
