sudo: required
dist: trusty
os:   linux
language: cpp
compiler:
    - gcc
    - clang
before_install:
    - test -n $CC && unset CC
    - test -n $CXX && unset CXX
install:
    - sudo apt-get -qq update
    - sudo apt-get install cmake
    - sudo apt-get install libpapi-dev
    - sudo apt-get install libhwloc-plugins
    - sudo apt-get install libhwloc-dev
    - sudo apt-get install libopenmpi-dev
    - sudo apt-get install openmpi-bin
    - sudo apt-get install openmpi-common
    - sudo apt-get install libhdf5-openmpi-dev
script:
    - chmod a+x dash/scripts/dash-ci.sh
    - ./dash/scripts/dash-ci.sh
after_failure:
    - cat ./build-ci/*/*/*.log
