sudo: required
dist: trusty
os:   linux
services:
    - docker
language: cpp
compiler:
    - gcc
before_install:
    - docker build --tag=dash/testing ./dash/scripts/docker-testing/
script:
    - docker run -v $PWD:/opt/dash dash/testing /bin/sh -c "export MPI_EXEC_FLAGS='--allow-run-as-root'; export DASH_MAX_UNITS='2'; cd /opt/dash; sh dash/scripts/dash-ci.sh | grep -v 'LOG =' | tee dash-ci.log 2> dash-ci.err;"
    - cat ./dash-ci.log | grep "PASSED" || return 1
after_script:
    - cat ./dash-ci.log
    - cat ./dash-ci.err
after_failure:
    - cat ./build-ci/*/*/build.log
