sudo: required
dist: trusty
os:   linux
services:
    - docker
language: cpp
compiler:
    - gcc
before_install:
    - docker pull dashproject/ci-testing:mpich
script:
    - sh ./dash/scripts/travisci/run-docker.sh 
    - cat ./dash-ci.log | grep "PASSED" || return 1
after_script:
    - cat ./build-ci/*/*/test_mpi.log | grep -v "LOG"
after_failure:
    - cat ./dash-ci.err
    - cat ./build-ci/*/*/build.log
